2022-01-21 19:02:05,147 - INFO - app.py - home - 31 - GET, ImmutableMultiDict([])
2022-01-21 19:02:05,154 - ERROR - app.py - error - 25 - index.html
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 34, in home
    render_template('index.html', saying=api_get()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-01-21 19:02:05,159 - ERROR - app.py - log_exception - 1457 - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 34, in home
    render_template('index.html', saying=api_get()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1393, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 26, in error
    return render_template('index.html', saying=api_get()['sayings'], msg='发生了错误')
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-01-21 19:02:05,172 - ERROR - app.py - error - 25 - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 34, in home
    render_template('index.html', saying=api_get()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1393, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 26, in error
    return render_template('index.html', saying=api_get()['sayings'], msg='发生了错误')
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-01-21 19:03:28,423 - INFO - app.py - home - 31 - GET, ImmutableMultiDict([])
2022-01-21 19:03:28,428 - ERROR - app.py - error - 25 - index.html
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 34, in home
    render_template('index.html', saying=api_get()['sayings'], msg='', uid=uid)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-01-21 19:03:28,435 - ERROR - app.py - log_exception - 1457 - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 34, in home
    render_template('index.html', saying=api_get()['sayings'], msg='', uid=uid)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1393, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 26, in error
    return render_template('index.html', saying=api_get()['sayings'], msg='发生了错误')
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-01-21 19:03:28,437 - ERROR - app.py - error - 25 - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 34, in home
    render_template('index.html', saying=api_get()['sayings'], msg='', uid=uid)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1393, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 26, in error
    return render_template('index.html', saying=api_get()['sayings'], msg='发生了错误')
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-01-21 19:03:53,662 - INFO - app.py - home - 31 - GET, ImmutableMultiDict([])
2022-01-21 19:03:53,671 - ERROR - app.py - error - 25 - index.html
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 34, in home
    render_template('index.html', saying=api_get()['sayings'], msg='', uid=uid)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-01-21 19:03:53,676 - ERROR - app.py - log_exception - 1457 - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 34, in home
    render_template('index.html', saying=api_get()['sayings'], msg='', uid=uid)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1393, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 26, in error
    return render_template('index.html', saying=api_get()['sayings'], msg='发生了错误')
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-01-21 19:03:53,677 - ERROR - app.py - error - 25 - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 34, in home
    render_template('index.html', saying=api_get()['sayings'], msg='', uid=uid)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1393, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 26, in error
    return render_template('index.html', saying=api_get()['sayings'], msg='发生了错误')
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2022-01-21 19:04:39,821 - INFO - app.py - home - 31 - GET, ImmutableMultiDict([])
2022-01-21 19:04:47,643 - ERROR - app.py - error - 25 - 405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\werkzeug\routing.py", line 2036, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2022-01-21 19:05:46,064 - ERROR - app.py - error - 25 - 405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\werkzeug\routing.py", line 2036, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2022-01-21 19:05:50,190 - INFO - app.py - put - 42 - POST, ImmutableMultiDict([('msg', '测试')])
2022-01-21 19:05:50,198 - INFO - app.py - home - 31 - GET, ImmutableMultiDict([])
2022-01-21 19:07:36,340 - INFO - app.py - put - 42 - POST, ImmutableMultiDict([('msg', 'ddd')])
2022-01-21 19:07:36,349 - INFO - app.py - home - 31 - GET, ImmutableMultiDict([])
2022-01-21 19:09:32,966 - INFO - app.py - put - 42 - POST, ImmutableMultiDict([('msg', 'ddd')])
2022-01-21 19:09:32,976 - INFO - app.py - home - 31 - GET, ImmutableMultiDict([])
2022-01-21 19:10:13,066 - INFO - app.py - home - 31 - GET, ImmutableMultiDict([])
2022-01-21 19:10:13,934 - INFO - app.py - home - 31 - GET, ImmutableMultiDict([])
2022-01-21 19:12:09,894 - INFO - app.py - put - 41 - POST, ImmutableMultiDict([('msg', '测试')])
2022-01-21 19:14:33,032 - INFO - app.py - put - 41 - POST, ImmutableMultiDict([('msg', 'ddd')])
2022-01-21 19:15:34,068 - INFO - app.py - put - 41 - POST, ImmutableMultiDict([('msg', 'ddd')])
2022-01-21 19:15:34,069 - INFO - app.py - put - 43 - ddd
2022-01-21 19:16:06,178 - INFO - app.py - put - 41 - POST, ImmutableMultiDict([('msg', 'dddd')])
2022-01-21 19:16:06,181 - ERROR - app.py - error - 25 - No transaction is begun.
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 54, in put
    db_session.commit()
  File "<string>", line 2, in commit
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1429, in commit
    raise sa_exc.InvalidRequestError("No transaction is begun.")
sqlalchemy.exc.InvalidRequestError: No transaction is begun.
2022-01-21 19:17:10,747 - INFO - app.py - put - 41 - POST, ImmutableMultiDict([('msg', 'ddd')])
2022-01-21 19:17:10,748 - ERROR - app.py - error - 25 - No transaction is begun.
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 54, in put
    db_session.commit()
  File "<string>", line 2, in commit
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1429, in commit
    raise sa_exc.InvalidRequestError("No transaction is begun.")
sqlalchemy.exc.InvalidRequestError: No transaction is begun.
2022-01-21 19:17:29,836 - INFO - app.py - put - 41 - POST, ImmutableMultiDict([('msg', 'ddd')])
2022-01-21 19:17:29,838 - ERROR - app.py - error - 25 - No transaction is begun.
Traceback (most recent call last):
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\app.py", line 54, in put
    db_session.commit()
  File "<string>", line 2, in commit
  File "C:\Users\gggxbbb\PycharmProjects\SuyanSuyu\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1429, in commit
    raise sa_exc.InvalidRequestError("No transaction is begun.")
sqlalchemy.exc.InvalidRequestError: No transaction is begun.
2022-01-21 19:19:29,704 - INFO - app.py - put - 41 - POST, ImmutableMultiDict([('msg', 'ddd')])
2022-01-21 19:19:36,742 - INFO - app.py - put - 41 - POST, ImmutableMultiDict([('msg', '测试测试')])
2022-01-21 19:24:39,151 - INFO - app.py - put - 41 - POST, ImmutableMultiDict([('msg', '测试，测试\r\n\r\n\r\n测试')])
